### ISSUE TITLE
getActionById no longer has setState()

### ISSUE THREAD

**Issue by logicallysynced** [elgatosf/streamdeck#54]
With the new 1.0 release, `getActionById` no longer has `setState()`. It seems to also be missing from event scopes also (`ev.action.setState()`). What is the recommended remediation here?

**Comment by logicallysynced** [comment]
Actually it seems you've scoped them now, so you need to add:

`if (! getActionById(id).isKey()) return;`

to have them resolvable.

This should be added to the UPGRADE doc ideally.

**Comment by GeekyEggo** [comment]
Hi @logicallysynced, I've updated the ["Keys and Dials"](https://github.com/elgatosf/streamdeck/blob/main/UPGRADE.md#keys-and-dials) section of the upgrade path to now provide the list of impacted methods — apologies for any inconvenience caused. 🙏
