### ISSUE TITLE
Debug not working?

### ISSUE THREAD

**Issue by wesbos** [elgatosf/streamdeck#74]
Hello - trying to get a simple app up and running and I cannot for the life of me get anything to log.

I've use the default counter example,and tried:

1. `console.log('hi')`
2. Set `streamDeck.logger.setLevel(LogLevel.DEBUG);`
3. `streamDeck.logger.debug('hi');` and all other log levels
4. Custom `"Debug": "--inspect=127.0.0.1:12345"` in the manifest.json file - chrome does not recognize the inspect instance running. 

I just want to see a string in my terminal when I press a button and no combination of the above seems to work.

I'm on Node v23.1.0

I've read the docs through but can't seem to get it working. Am I missing something? Or a bug?

**Comment by wesbos** [comment]
I should note I do see log files being created in the logs folder, but I can't imagine thats the only way to view them? Doesnt seem to log objects either

**Comment by GeekyEggo** [comment]
Hey Wes, the `streamDeck.logger` console target is currently only available whilst the plugin is being debugged. This is something we'd like to improve, but for now, you should be able to see them via either:

**Chrome**

1. Specify a debug port within the manifest (`"Debug": "--inspect=127.0.0.1:12345"` is perfect).
2. On Chrome's inspect page (`chrome://inspect/#devices`), configure "Discover network targets" to monitor `localhost:12345`.
3. Your plugin should show under the "Remote targets", under "Target (v20.18.0)". (this is the version of Node.js that ships with Stream Deck).

**VSCode**

1. With your plugin running, press `Ctrl` / `Cmd` + `P`
2. Search for `> Attach to Node Process`.
3. Select the `node20` instance that matches your plugin.
![image](https://github.com/user-attachments/assets/e4ee09e0-8e05-431e-86d8-6143afcf8ea7)

In relation to logging objects; the logger is currently capable of logging objects, but utilizes `JSON.stringify` so does come with some limitations. If you're seeing odd behaviour here, I'd be happy to investigate further — would it be possible to get a code snippet of the object you're wanting to log, and how you're attempting to log it?

**Comment by wesbos** [comment]
Hrmmm Yeah I tried all those things.  Let me make a simple counter example and try again.

**Comment by tiptronic** [comment]
...additionally to what @GeekyEggo already mentioned, you can also combine any of the above like so:
```javascript
export const wrappedLogger = (prefix) => {
	const logger = streamDeck.logger.createScope(`${prefix}`);
	const dbgFn = (...args) => {
		logger.info(wrapMessage(args));
                console.log(...args);
                ...
	}
	return dbgFn;
};
```
where `wrapMessage` is your privat stringify method...

If you have large JSON-objects Chrome's console has some nifty features (as you already know)

**Comment by wesbos** [comment]
Okay! Both your suggestions worked. Thank you - I had just expected that the console.log would work in the terminal, but the chrome/VS code logger is a better experience anyways. 

Thank you for the quick help - and great job on this SDK!
