### ISSUE TITLE
how use axios in plugin?

### ISSUE THREAD

**Issue by loveRandy** [elgatosf/streamdeck#76]
how use axios in plugin?

**Comment by tiptronic** [comment]
`npm install axios`

**Comment by GeekyEggo** [comment]
Hi Randy, as tiptronic has suggested, it's as easy as installing axios with npm in the terminal, for example:
```
npm i axios
```

One thing to consider — as Stream Deck plugins run in a Node.js 20.18 environment, you may not need Axios. Alternatively, you may be able to use the built-in [`fetch`](https://nodejs.org/docs/latest-v20.x/api/globals.html#fetch) global (see also [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/fetch)) for what you needs. This [article from LogRocket](https://blog.logrocket.com/axios-vs-fetch-best-http-requests/) goes into more detail of Axios vs `fetch`

**Comment by loveRandy** [comment]
@GeekyEggo @tiptronic Thank you both. When npm i axos .I have resolved the problem.But i need to install @rollup/plugin-json and use this plugin in rollup.config.mjs, or there will be another problem caused.
